#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use Lox;

if (@ARGV > 1) {
  print "Usage: lox [script]\n";
  exit 64;
}
elsif (@ARGV == 1) {
  Lox::run_file($ARGV[0]);
}
else {
  Lox::run_prompt();
}
